### PR TITLE
Fix for 483

### LINKED ISSUE #483: seg fault error
The error occurs for test_float_matrix_mul, when the host is copying the result from device to host.

```
Dumping VCS Annotated Stack:
#0  0x0000155545aa841c in waitpid () from /lib64/libc.so.6
#1  0x0000155545a25f12 in do_system () from /lib64/libc.so.6
#2  0x0000155550a3766c in SNPSle_10ee25eff68cd8461c9146fa1d0b35e87067f3c8015b313e639d2928478c79b3f673f99203bcf8be64600612100082236bffb2007f1e0ef9 () from /gro/cad/synopsys/vcs-mx/O-2018.09-SP2-6/linux64/lib/liberrorinf.so
#3  0x0000155550a391ae in SNPSle_10ee25eff68cd8461c9146fa1d0b35e87067f3c8015b313efba706aab251478fa49e66610e453774633a6c152e7ef778f2202cda681f3d4e () from /gro/cad/synopsys/vcs-mx/O-2018.09-SP2-6/linux64/lib/liberrorinf.so
#4  0x0000155550a31b33 in SNPSle_d35ca1ff70d465c2b9b1a72eee90a506fdd009d3de3db1de () from /gro/cad/synopsys/vcs-mx/O-2018.09-SP2-6/linux64/lib/liberrorinf.so
#5  0x000015554cc25f9f in SNPSle_64133461705005bb725549e2e6fa1b3f () from /gro/cad/synopsys/vcs-mx/O-2018.09-SP2-6/linux64/lib/libvcsnew.so
#6  0x000015554ca5ff69 in SNPSle_82244d58c54c18c70d63edc9becab634 () from /gro/cad/synopsys/vcs-mx/O-2018.09-SP2-6/linux64/lib/libvcsnew.so
#8  0x0000155555109c99 in hb_mc_npa_get_epa () from //bsg/bsg_bladerunner/bsg_f1/libraries/libbsg_manycore_runtime.so.1
#9  0x000015555510c78c in hb_mc_manycore_recv_read_rsp(hb_mc_manycore*, hb_mc_npa_t const*, void*, unsigned long, unsigned int*) () from //bsg/bsg_bladerunner/bsg_f1/libraries/libbsg_manycore_runtime.so.1
#10 0x000015555510d94d in int hb_mc_manycore_read_mem_internal<unsigned int, unsigned int*, hb_mc_manycore_read_mem::npa_function>(hb_mc_manycore*, hb_mc_manycore_read_mem::npa_function, unsigned int*&, unsigned long) () from //bsg/bsg_bladerunner/bsg_f1/libraries/libbsg_manycore_runtime.so.1
#11 0x000015555510cedb in hb_mc_manycore_read_mem () from //bsg/bsg_bladerunner/bsg_f1/libraries/libbsg_manycore_runtime.so.1
#12 0x00001555551186c6 in hb_mc_manycore_eva_read () from //bsg/bsg_bladerunner/bsg_f1/libraries/libbsg_manycore_runtime.so.1
#13 0x0000155555112b4e in hb_mc_device_memcpy () from //bsg/bsg_bladerunner/bsg_f1/libraries/libbsg_manycore_runtime.so.1
#14 0x000000000041155f in kernel_float_matrix_mul (argc=3, argv=0x1555382d5e70) at //bsg/bsg_bladerunner/bsg_f1/regression/cuda//test_float_matrix_mul.c:220
#15 0x000000000041190c in cosim_main (exit_code=0x1555387e26d0, args=0x155555393f60 "//bsg/bsg_bladerunner/bsg_manycore/software/spmd/bsg_cuda_lite_runtime//float_matrix_mul/main.riscv") at //bsg/bsg_bladerunner/bsg_f1/regression/cuda//test_float_matrix_mul.c:287
#16 0x000015555202fbe5 in T_VCSgd_g7hgQ_55_0 () from //bsg/bsg_bladerunner/bsg_f1/testbenches/cuda/test_float_matrix_mul.daidir/_47920_archive_1.so
#17 0x000015554e00b2ab in SNPSle_8019c4c21dc45cf13790e71a253a4d8d () from /gro/cad/synopsys/vcs-mx/O-2018.09-SP2-6/linux64/lib/libvcsnew.so
#18 0x000015553b481740 in ?? ()
#19 0x000015553b4816c0 in ?? ()
#20 0x000015553b4816d8 in ?? ()
#21 0x0000000000000000 in ?? ()

```

### PR DESCRIPTION
**Pull request by mrutt92**
* fixes #483
* decouples reading response packets from the masking of response data

### CODE REVIEW

File: libraries/bsg_manycore.cpp [hunk 1]
```diff
@@ -1362,38 +1363,62 @@ static int hb_mc_manycore_recv_read_rsp(hb_mc_manycore_t *mc,
...
+        static_assert(sizeof(UINT) == 1 || sizeof(UINT) == 2 || sizeof(UINT) == 4,
+                      "hb_mc_manycore_mask_load_data: UINT must be uint8_t, uint16_t, or uint32_t");
+
+        if (sizeof(UINT) == 4) {
+                result = load_data;
+        } else if (sizeof(UINT) == 2) {
+                result = (load_data >> shift) & 0xFFFF;
+        } else if (sizeof(UINT) == 1) {
+                result = (load_data >> shift) & 0xFF;
+        }
```
Comment (tommydcjung) [inline libraries/bsg_manycore.cpp]: if you are loading half, and the byte offset is not half aligned, it should ignore the LSB to make it half-aligned?
Otherwise, for load-half across the word boundary, you need to do loads to support

Comment (mrutt92) [reply libraries/bsg_manycore.cpp]: Currently the comments that document the interface are pretty explicit that loads need to be aligned to their size. The buffered read function only supports reading word aligned/sized buffers and it explicitly checks those conditions and returns an error if they are not met.

**Comment by mrutt92** [comment]
all the regression tests pass in cosim.
